create table if not exists public.favorite_dogs (
  id bigint generated by default as identity primary key,
  breed text not null,
  image_url text not null,
  note text,
  created_at timestamptz default now()
);

alter table public.favorite_dogs enable row level security;

create policy "Allow public favorite dog reads"
on public.favorite_dogs
for select
to anon, authenticated
using (true);

create policy "Allow public favorite dog inserts"
on public.favorite_dogs
for insert
to anon, authenticated
with check (true);
